name: Crawler Trigger

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron
        run: |
          # Используем флаг -v (verbose) чтобы видеть заголовки
          # И флаг --fail чтобы Action падал, если сервер вернет ошибку (не 200)
          curl -v --fail -X GET "${{ secrets.VERCEL_URL }}/api/cron" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"