name: Crawler Trigger

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron
        env: 
          URL: ${{ secrets.VERCEL_URL }}
          TOKEN: ${{ secrets.CRON_SECRET }}
        run: |
          curl -v -L --fail "$URL/api/cron" \
          -H "Authorization: Bearer $TOKEN"